Name:           ros-lunar-sound-play
Version:        0.3.3
Release:        0%{?dist}
Summary:        ROS sound_play package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/sound_play
Source0:        %{name}-%{version}.tar.gz

Requires:       festival
Requires:       festvox-kal-diphone
Requires:       gstreamer1
Requires:       gstreamer1-plugins-base
Requires:       gstreamer1-plugins-good
Requires:       gstreamer1-plugins-ugly
Requires:       pygobject3
Requires:       ros-lunar-actionlib-msgs
Requires:       ros-lunar-audio-common-msgs
Requires:       ros-lunar-diagnostic-msgs
Requires:       ros-lunar-message-runtime
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-roslib
Requires:       ros-lunar-rospy
BuildRequires:  ros-lunar-actionlib
BuildRequires:  ros-lunar-actionlib-msgs
BuildRequires:  ros-lunar-audio-common-msgs
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-diagnostic-msgs
BuildRequires:  ros-lunar-message-generation
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-roslib

%description
sound_play provides a ROS node that translates commands on a ROS topic
(robotsound) into sounds. The node supports built-in sounds, playing OGG/WAV
files, and doing speech synthesis via festival. C++ and Python bindings allow
this node to be used without understanding the details of the message format,
allowing faster development and resilience to message format changes.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Tue May 22 2018 Austin Hendrix <namniart@gmail.com> - 0.3.3-0
- Autogenerated by Bloom

* Wed May 02 2018 Austin Hendrix <namniart@gmail.com> - 0.3.2-0
- Autogenerated by Bloom

